source 'http://rubygems.org'

gem 'rails', :git => 'http://github.com/rails/rails.git'
gem 'devise', :git => 'http://github.com/plataformatec/devise.git'
gem 'state_machine', :git => 'http://github.com/pluginaweek/state_machine.git'
gem "will_paginate", :git => 'http://github.com/mislav/will_paginate.git'
gem 'sunspot', :git => 'http://github.com/outoftime/sunspot.git'
gem 'sunspot_rails', :git => 'http://github.com/outoftime/sunspot.git'
gem 'haml', :git => 'http://github.com/nex3/haml.git'
gem 'oauth2', :git => 'http://github.com/intridea/oauth2.git'

gem 'high_voltage'
gem 'pg'
gem 'hoptoad_notifier'
gem 'nifty-generators'
